language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-003121

services:
  - docker

branches:
  only:
  - prod

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1

before_script:
  dotnet restore

script:
  dotnet publish -c Release

after_script:
  - docker build -t nerdcats/datacat:prod .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
  - docker push nerdcats/datacat:prod
  - "curl -H 'Content-Type: application/json' -X POST -d '{\"mode\": \"docker\", \"image\": \"nerdcats/datacat:prod\", \"arguments\": "-p 5000:5000"}' http://datacat,nerdcats.io?token=nerdcats"