version: '1.0.{build}'
image: Visual Studio 2017
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore 
build_script:
- dotnet publish -c release -r win10-x64
after_build:
- xcopy src\DataCat\appsettings.json src\DataCat\bin\Release\netcoreapp1.1\win10-x64\ /y 
artifacts:
- path: src\DataCat\bin\Release\netcoreapp1.1\win10-x64\publish
  name: datacat
  type: zip