/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Fri Feb 10 2017 20:58:15 GMT+0100 (W. Europe Standard Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {
    API_BASE: 'http://localhost:5000/api/',
};

//# sourceMappingURL=env.js.map
